project:
  type: website
  output-dir: docs

website:
  title: "The Far Right in Europe and beyond"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: content/index.qmd
        text: Content
      - href: resources/index.qmd
        text: Resources
      - href: report/index.qmd
        text: Report example


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



